# Generated by Django 3.1.2 on 2020-11-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmodels', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='json',
            field=models.TextField(null=True),
        ),
    ]
