# Generated by Django 3.1.2 on 2020-12-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmodels', '0003_message_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='check',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
